### ISSUE TITLE
PE: OK Button on startup player change modal dialog does not work.

### ISSUE THREAD

**Issue by Herrner** [EXMARaLDA/exmaralda#283]
When starting PE for the first time with a non-BAS audio player, the modal dialog(s) asking you to change player can't be closed via the `OK` button, only by closing the dialog with the top-right close button.

````
************* INFO **************
Date : Wed Oct 20 09:23:52 CEST 2021
Operating system : Linux
Operating system architecture : amd64
OS version : 5.13.0-19-generic
JRE version : 14.0.2
JRE vendor : AdoptOpenJDK
JVM version (specification/implementation) : 14 / 14.0.2+12
org.sfb538.exmaralda.PartiturEditor.PlayerType: JMF-Player
Java Class Path : /opt/partitureditor/lib/app/EXMARaLDA_NetBeans_Project.jar:/opt/partitureditor/lib/app/lib/saxon9.jar:/opt/partitureditor/lib/app/lib/javafx.fxml.jar:/opt/partitureditor/lib/app/lib/commons-lang-2.5.jar:/opt/partitureditor/lib/app/lib/jaxb-api-2.3.0.jar:/opt/partitureditor/lib/app/lib/httpcore-4.4.3.jar:/opt/partitureditor/lib/app/lib/weblicht.jar:/opt/partitureditor/lib/app/lib/javafx.swing.jar:/opt/partitureditor/lib/app/lib/javafx-controls-11-linux.jar:/opt/partitureditor/lib/app/lib/javafx.controls.jar:/opt/partitureditor/lib/app/lib/jaxen-1.1.6.jar:/opt/partitureditor/lib/app/lib/javafx.base.jar:/opt/partitureditor/lib/app/lib/ips.commons.jar:/opt/partitureditor/lib/app/lib/javafx-media-11-linux.jar:/opt/partitureditor/lib/app/lib/elan-5.8.jar:/opt/partitureditor/lib/app/lib/commons-io-2.4.jar:/opt/partitureditor/lib/app/lib/jctable.jar:/opt/partitureditor/lib/app/lib/bounce.jar:/opt/partitureditor/lib/app/lib/xercesImpl.jar:/opt/partitureditor/lib/app/lib/BATIK.jar:/opt/partitureditor/lib/app/lib/xalan.jar:/opt/partitureditor/lib/app/lib/javafx.web.jar:/opt/partitureditor/lib/app/lib/saxon9-dom.jar:/opt/partitureditor/lib/app/lib/httpmime-4.5.1.jar:/opt/partitureditor/lib/app/lib/javafx-swing-11-linux.jar:/opt/partitureditor/lib/app/lib/javafx-base-11-linux.jar:/opt/partitureditor/lib/app/lib/commons-logging-1.2.jar:/opt/partitureditor/lib/app/lib/tt4j.jar:/opt/partitureditor/lib/app/lib/javafx-graphics-11-linux.jar:/opt/partitureditor/lib/app/lib/stax-utils.jar:/opt/partitureditor/lib/app/lib/javafx.graphics.jar:/opt/partitureditor/lib/app/lib/ips.audiotools.jar:/opt/partitureditor/lib/app/lib/httpclient-4.5.1.jar:/opt/partitureditor/lib/app/lib/jdom.jar:/opt/partitureditor/lib/app/lib/jcalendar-1.4.jar:/opt/partitureditor/lib/app/lib/serializer.jar:/opt/partitureditor/lib/app/lib/javafx.media.jar
Java Library Path: /opt/partitureditor\app\native
Application name :Partitur-Editor
Application version :1.7
Build time :20210326.1635
http://www.exmaralda.org
*********************************
Default player: BAS-Audio-Player
User's player: JMF-Player
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Trying to unblock window blocked by another dialog
	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(Unknown Source)
	at java.desktop/sun.awt.X11.XWindowPeer.setModalBlocked(Unknown Source)
	at java.desktop/java.awt.Window.setModalBlocked(Unknown Source)
	at java.desktop/java.awt.Dialog.unblockWindow(Unknown Source)
	at java.desktop/java.awt.Dialog.modalHide(Unknown Source)
	at java.desktop/java.awt.Dialog.hideAndDisposePreHandler(Unknown Source)
	at java.desktop/java.awt.Dialog.hide(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at java.desktop/javax.swing.JOptionPane$1.propertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.awt.Component.firePropertyChange(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.setValue(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicOptionPaneUI$ButtonActionListener.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(Unknown Source)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.makePlayer(PartitureTableWithActions.java:2615)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.<init>(PartitureTableWithActions.java:244)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.<init>(PartitureTableWithActions.java:231)
	at org.exmaralda.partitureditor.partiture.PartiturEditor.<init>(PartiturEditor.java:107)
	at org.exmaralda.partitureditor.partiture.PartiturEditor$4.run(PartiturEditor.java:297)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
````

**Comment by berndmoos** [comment]
Can't really see what is going wrong here. The build is from March 2021, and quite a few things have changed since then with respect to the players. Maybe this would be fixed with a new Linux build (can't do at the moment), maybe it is a sun.awt.X11 specific problem -- can't tell, need a Linux desktop :-( Leaving this open.

**Comment by berndmoos** [comment]
@Herrner : preview is updated. Can you check puh-leeze?

**Comment by hannahedeland** [comment]
I tried starting P-E with JavaFX set on Linux Mint 20.2, was informed that I should rather use BAS player, clicked Ja, got another dialog to restart, klicked OK and P-E restarted with BAS set, no problems with this part...

**Comment by Herrner** [comment]
Also doesn't happen on Ubuntu 21.10 w/ Wayland anymore. Closing.
