### ISSUE TITLE
FOLKER does not start on Linux

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#294]
```
************* INFO **************
Date : Sun Nov 14 11:00:40 CET 2021
Operating system : Linux
Operating system architecture : amd64
OS version : 5.4.0-86-generic
JRE version : 1.8.0_111
JRE vendor : Oracle Corporation
JVM version (specification/implementation) : 1.8 / 25.111-b14
org.sfb538.exmaralda.PartiturEditor.PlayerType: BAS-Audio-Player
Java Class Path : ./lib/EXMARaLDA.jar:./lib/jctable.jar:./lib/jdom.jar:./lib/xalan.jar:./lib/xercesImpl.jar:./lib/xml-apis.jar:./lib/saxon9he.jar:./lib/serializer.jar:./lib/jaxen-1.1.6.jar:./lib/mrj.jar:./lib/AppleJavaExtensions.jar:./lib/QTJava.zip:./lib/fobs4jmf.jar:./lib/jmf.jar:./lib/ipsk.jar:./lib/elan.jar:./lib/tritonus_share-0.3.6.jar:./lib/httpcore-4.4.3.jar:./lib/httpclient-4.5.1.jar:./lib/httpmime-4.5.1.jar:./lib/commons-logging-1.2.jar:./lib/swing-worker-1.2.jar
Application name :Folker
Application version :1.2.1
Build time :20191008.0955
http://www.exmaralda.org
*********************************
started reading Internationalization file...
Internationalization file read.
Default player: JMF-Player
Initializing search dialog
started reading document...
document read.
Search dialog initialized
started reading document...
document read.
TIME: 29
TIME2: 21
TIME3: 19
TIMEX: 79
CHECK_REGEX _?((\(([a-zäöüß]++(?!°)|(\+{3}+)++)(( |_)([a-zäöüß]++(?!°)|(\+{3}+)++))*+(/([a-zäöüß]++(?!°)|(\+{3}+)++)(( |_)([a-zäöüß]++(?!°)|(\+{3}+)++))*+)*+\)|([a-zäöüß]++(?!°)|(\+{3}+)++)|([a-zäöüß]++(?!°)|(\+{3}+)++)(_([a-zäöüß]++(?!°)|(\+{3}+)++))++|\({2}+[^\(-\.\d][^\)]*\){2}+|(\((-{1,3}|\.)\)|\(\d{1,2}\.\d{1,2}\))|(°h{1,3}+|h{1,3}+°)(?= ))( ))*+(\(([a-zäöüß]++(?!°)|(\+{3}+)++)(( |_)([a-zäöüß]++(?!°)|(\+{3}+)++))*+(/([a-zäöüß]++(?!°)|(\+{3}+)++)(( |_)([a-zäöüß]++(?!°)|(\+{3}+)++))*+)*+\)|([a-zäöüß]++(?!°)|(\+{3}+)++)|([a-zäöüß]++(?!°)|(\+{3}+)++)(_([a-zäöüß]++(?!°)|(\+{3}+)++))++|\({2}+[^\(-\.\d][^\)]*\){2}+|(\((-{1,3}|\.)\)|\(\d{1,2}\.\d{1,2}\))|(°h{1,3}+|h{1,3}+°)(?= ))? ?
Player: JMF-Player
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.exmaralda.folker.videopanel.VideoPanel.<init>(VideoPanel.java:53)
	at org.exmaralda.folker.application.ApplicationControl.initVideoPanel(ApplicationControl.java:998)
	at org.exmaralda.folker.application.ApplicationControl.<init>(ApplicationControl.java:288)
	at org.exmaralda.folker.application.ApplicationFrame.<init>(ApplicationFrame.java:40)
	at org.exmaralda.folker.application.ApplicationFrame$5.run(ApplicationFrame.java:204)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.exmaralda.folker.application.ApplicationControl.componentResized(ApplicationControl.java:2741)
	at java.awt.Component.processComponentEvent(Component.java:6359)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Window.processEvent(Window.java:2025)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
This is AudioPanel.formComponentResized.
This is AudioPanel.formComponentResized.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.exmaralda.folker.videopanel.VideoPanel.formComponentResized(VideoPanel.java:165)
	at org.exmaralda.folker.videopanel.VideoPanel.access$000(VideoPanel.java:26)
	at org.exmaralda.folker.videopanel.VideoPanel$1.componentResized(VideoPanel.java:81)
	at java.awt.Component.processComponentEvent(Component.java:6359)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Window.processEvent(Window.java:2025)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by Herrner** [comment]
Original bug report was on Linux Mint 20. Can reproduce on Ubuntu 21.04. Startup script also gives an error  
`Failed to load module canberra-gtk-module`
Installing canberra-gtk via `sudo apt install libcanberra-gtk-module libcanberra-gtk3-module` does not fix the startup problem.

**Comment by berndmoos** [comment]
N.B.: Build time for the original bug report is 2019.

**Comment by Herrner** [comment]
Oh, so this is not the error from 2011-11-14... nevermind, then.

**Comment by Herrner** [comment]
...same here.

**Comment by hannahedeland** [comment]
i just started FOLKER using the current preview version on Linux Mint 20.2, no problems, log looks clean, is this good or bad?

**Comment by berndmoos** [comment]
> i just started FOLKER using the current preview version on Linux Mint 20.2, no problems, log looks clean, is this good or bad?

Good. What build time is this? I may just need to make a new Linux build, because this is related to the players.

**Comment by hannahedeland** [comment]
> > i just started FOLKER using the current preview version on Linux Mint 20.2, no problems, log looks clean, is this good or bad?
> 
> Good. What build time is this? I may just need to make a new Linux build, because this is related to the players.

log says: Build time :20210326.1635

**Comment by berndmoos** [comment]
It may also depend on which installer is used. The first three gz.tar are probably from 2019, so they should go. The deb package does not always work afaik. The last one is the best, and I'll update this ... sometime ... soon. I don't have a running Linux any more :-(

**Comment by berndmoos** [comment]
@Herrner : The tar.gz preview version is now updated. Can you try puh-leeze?

**Comment by berndmoos** [comment]
@Herrner : https://www.youtube.com/watch?v=j9R5s43KRqs?

**Comment by berndmoos** [comment]
It did start with the current preview, so closing this.
