### ISSUE TITLE
BAS Player: trouble with URI

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#321]
Error message: URI is not absolute, need to prepend "file:///"

**Comment by berndmoos** [comment]
Also need to escape space with %20

**Comment by berndmoos** [comment]
It still fails with this:

`..\EXMARaLDA_Support\2023_03_09_ISSUE_321\A väry adväntscherus folder näim wizz # special sym+bols\Paul Mc Späces.wav`

**Comment by berndmoos** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: URI has a fragment component
	at java.base/java.io.File.<init>(Unknown Source)
	at org.exmaralda.partitureditor.sound.BASAudioPlayer.setSoundFile(BASAudioPlayer.java:76)

```

**Comment by berndmoos** [comment]
It is working now on Windows unless you have a filename with very stupid special symbols in which case the solution is to stop having a filename with very stupid special symbols. Need to check this on MAC and Linux, too.

**Comment by berndmoos** [comment]
Tested now on Windows and Intel Mac without any apparent problems
