### ISSUE TITLE
Bug in masking: Internal SER file not read

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#372]
```
[*** MaskAction ***]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[], int, int)" because "this.in" is null
	at java.base/java.io.ObjectInputStream$PeekInputStream.read(Unknown Source)
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
	at java.base/java.io.ObjectInputStream.readStreamHeader(Unknown Source)
	at java.base/java.io.ObjectInputStream.<init>(Unknown Source)
	at org.exmaralda.masker.Masker.initBrownNoiseWavFile(Masker.java:69)
	at org.exmaralda.masker.Masker.<init>(Masker.java:48)
	at org.exmaralda.folker.application.ApplicationControl.mask(ApplicationControl.java:3143)
	at org.exmaralda.folker.actions.transcriptionactions.MaskAction.actionPerformed(MaskAction.java:33)

```

**Comment by berndmoos** [comment]
Funnily, this only happens in the distributed version, not in NetBeans

**Comment by berndmoos** [comment]
`**/masker/*` (where the ser is) was excluded from the build jar. This is very stupid.

**Comment by berndmoos** [comment]
Fixed it
