### ISSUE TITLE
Dependencies missing for SVG panel

### ISSUE THREAD

**Issue by berndmoos** [EXMARaLDA/exmaralda#438]
`java.lang.NoClassDefFoundError: org/w3c/dom/Window
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)`

**Comment by berndmoos** [comment]
The class is there in BATIK.jar May be a problem with Java > 8:

* See https://elbosso.github.io/batik_java9_modulsystem_____9760_.html
* https://issues.apache.org/jira/browse/BATIK-1216

**Comment by berndmoos** [comment]
Replacing the BATIK.jar with a new (batik 1.17) jar helped. The new jar is 8MB larger than the old one, though.

![image](https://github.com/Exmaralda-Org/exmaralda/assets/13796493/fcc9834d-440a-44e5-a9a3-02b406c9cde1)
